### ISSUE TITLE
How to use API?

### ISSUE THREAD

**Issue by melnikaite** [CHURPTeam/CHURP#6]
After running `./simple.sh 5 2` inside container I got 6 listened ports
```
127.0.0.1:11000
127.0.0.1:11001
127.0.0.1:11002
127.0.0.1:11003
127.0.0.1:11004
127.0.0.1:11005
```
How to call `changeCommittee` and other methods mentioned in `README.md`?

It seems that nodes are using gRPC interface to interact with each other, I found `src/services/services.proto` to generate gRPC client, but it doesn't contain neither `changeCommittee` nor other methods from `README.md`.

**Comment by bcuestav** [comment]
same problem! Nobody answered?

**Comment by mskd12** [comment]
The script `simple.sh` is meant for demo purposes. It executes the committee handoff directly, so you do not need to call any function specifically. The README might be a little confusing in that we do not actually have a `changeCommittee` method, and the API description was meant for explanation purposes only. The handoff is internally implemented via three phases and the corresponding services can be found inside `src/services/services.proto`.
